# NAME: docker-compose.yml
# AUTH: Ryan McCartney <ryan@mccartney.info>
# DATE: 30/10/2023
# DESC: Run ffmpeg-docker prebuilt version

services:
    ffmpeg:
        image: ghcr.io/ryanmccartney/ffmpeg-docker:latest
        restart: always
        volumes:
            - ./data:/home/node/app/data
        environment:
            PORT: 4566
            WEB_GUI: "true"
            NODE_ENV: "production"
        #network_mode: "host"
        ports:
            - 4566:4566
